/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: f0ef45e37c9023d37af58209b4c99fb8)
interface __BaseEnv_Env {
	KV: KVNamespace;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
